"""Realistic sample portfolio data for the DEI Risk Engine."""

from .models import CompanyProfile


SAMPLE_COMPANIES = [
    CompanyProfile(
        company_name="NorthStar Health Network",
        industry="healthcare",
        annual_revenue=420_000_000,
        employee_count=3_800,
        data_sensitivity="high",
        cloud_dependency="high",
        remote_workforce_percentage=62,
        third_party_vendor_exposure="high",
        security_maturity="medium",
        historical_incident_count=2,
        regulatory_exposure="high",
    ),
    CompanyProfile(
        company_name="Meridian Bank Group",
        industry="finance",
        annual_revenue=1_800_000_000,
        employee_count=5_400,
        data_sensitivity="high",
        cloud_dependency="medium",
        remote_workforce_percentage=35,
        third_party_vendor_exposure="medium",
        security_maturity="high",
        historical_incident_count=1,
        regulatory_exposure="high",
    ),
    CompanyProfile(
        company_name="ShopSphere Retail",
        industry="retail",
        annual_revenue=760_000_000,
        employee_count=8_900,
        data_sensitivity="medium",
        cloud_dependency="high",
        remote_workforce_percentage=48,
        third_party_vendor_exposure="high",
        security_maturity="medium",
        historical_incident_count=3,
        regulatory_exposure="medium",
    ),
    CompanyProfile(
        company_name="CloudForge Labs",
        industry="technology",
        annual_revenue=310_000_000,
        employee_count=1_250,
        data_sensitivity="medium",
        cloud_dependency="high",
        remote_workforce_percentage=84,
        third_party_vendor_exposure="medium",
        security_maturity="high",
        historical_incident_count=0,
        regulatory_exposure="medium",
    ),
    CompanyProfile(
        company_name="GraniteWorks Manufacturing",
        industry="manufacturing",
        annual_revenue=540_000_000,
        employee_count=4_700,
        data_sensitivity="medium",
        cloud_dependency="medium",
        remote_workforce_percentage=18,
        third_party_vendor_exposure="medium",
        security_maturity="low",
        historical_incident_count=2,
        regulatory_exposure="medium",
    ),
    CompanyProfile(
        company_name="Greenfield University",
        industry="education",
        annual_revenue=920_000_000,
        employee_count=6_200,
        data_sensitivity="high",
        cloud_dependency="medium",
        remote_workforce_percentage=44,
        third_party_vendor_exposure="medium",
        security_maturity="medium",
        historical_incident_count=2,
        regulatory_exposure="high",
    ),
    CompanyProfile(
        company_name="HarborLine Logistics",
        industry="logistics",
        annual_revenue=690_000_000,
        employee_count=3_100,
        data_sensitivity="low",
        cloud_dependency="low",
        remote_workforce_percentage=12,
        third_party_vendor_exposure="high",
        security_maturity="low",
        historical_incident_count=1,
        regulatory_exposure="low",
    ),
    CompanyProfile(
        company_name="BrightCart Payments",
        industry="finance",
        annual_revenue=260_000_000,
        employee_count=740,
        data_sensitivity="high",
        cloud_dependency="high",
        remote_workforce_percentage=73,
        third_party_vendor_exposure="high",
        security_maturity="low",
        historical_incident_count=4,
        regulatory_exposure="high",
    ),
    CompanyProfile(
        company_name="CivicAid Nonprofit",
        industry="nonprofit",
        annual_revenue=85_000_000,
        employee_count=420,
        data_sensitivity="medium",
        cloud_dependency="medium",
        remote_workforce_percentage=58,
        third_party_vendor_exposure="low",
        security_maturity="medium",
        historical_incident_count=0,
        regulatory_exposure="medium",
    ),
    CompanyProfile(
        company_name="Pinnacle Legal Partners",
        industry="legal",
        annual_revenue=140_000_000,
        employee_count=880,
        data_sensitivity="high",
        cloud_dependency="medium",
        remote_workforce_percentage=69,
        third_party_vendor_exposure="medium",
        security_maturity="high",
        historical_incident_count=1,
        regulatory_exposure="high",
    ),
    CompanyProfile(
        company_name="Aster Medical Devices",
        industry="manufacturing",
        annual_revenue=1_100_000_000,
        employee_count=5_950,
        data_sensitivity="high",
        cloud_dependency="medium",
        remote_workforce_percentage=28,
        third_party_vendor_exposure="high",
        security_maturity="medium",
        historical_incident_count=2,
        regulatory_exposure="high",
    ),
    CompanyProfile(
        company_name="NovaGrid Energy Services",
        industry="technology",
        annual_revenue=880_000_000,
        employee_count=2_600,
        data_sensitivity="medium",
        cloud_dependency="high",
        remote_workforce_percentage=52,
        third_party_vendor_exposure="high",
        security_maturity="medium",
        historical_incident_count=1,
        regulatory_exposure="medium",
    ),
    CompanyProfile(
        company_name="Fairway Mutual Insurance",
        industry="finance",
        annual_revenue=640_000_000,
        employee_count=2_300,
        data_sensitivity="high",
        cloud_dependency="medium",
        remote_workforce_percentage=41,
        third_party_vendor_exposure="medium",
        security_maturity="medium",
        historical_incident_count=0,
        regulatory_exposure="high",
    ),
    CompanyProfile(
        company_name="MetroLearn Charter Network",
        industry="education",
        annual_revenue=120_000_000,
        employee_count=1_600,
        data_sensitivity="medium",
        cloud_dependency="high",
        remote_workforce_percentage=23,
        third_party_vendor_exposure="medium",
        security_maturity="low",
        historical_incident_count=1,
        regulatory_exposure="medium",
    ),
    CompanyProfile(
        company_name="Trailhead Outdoor Retail",
        industry="retail",
        annual_revenue=210_000_000,
        employee_count=2_800,
        data_sensitivity="medium",
        cloud_dependency="medium",
        remote_workforce_percentage=16,
        third_party_vendor_exposure="medium",
        security_maturity="high",
        historical_incident_count=0,
        regulatory_exposure="low",
    ),
    CompanyProfile(
        company_name="BlueRiver Community Health",
        industry="healthcare",
        annual_revenue=155_000_000,
        employee_count=1_100,
        data_sensitivity="high",
        cloud_dependency="medium",
        remote_workforce_percentage=31,
        third_party_vendor_exposure="medium",
        security_maturity="low",
        historical_incident_count=3,
        regulatory_exposure="high",
    ),
    CompanyProfile(
        company_name="VectorGate Logistics",
        industry="logistics",
        annual_revenue=980_000_000,
        employee_count=7_400,
        data_sensitivity="low",
        cloud_dependency="high",
        remote_workforce_percentage=26,
        third_party_vendor_exposure="high",
        security_maturity="medium",
        historical_incident_count=1,
        regulatory_exposure="medium",
    ),
    CompanyProfile(
        company_name="OpenHands Relief Fund",
        industry="nonprofit",
        annual_revenue=48_000_000,
        employee_count=260,
        data_sensitivity="medium",
        cloud_dependency="high",
        remote_workforce_percentage=76,
        third_party_vendor_exposure="medium",
        security_maturity="low",
        historical_incident_count=2,
        regulatory_exposure="medium",
    ),
]
